---
language: php
php:
  - '7.1'
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files

install: composer install

script: deploy.sh

env:
  global:
    - secure: "acdcfl4w82E936CnY1ae4tnRInp14QA67OI568WiPIouopklDUUnjEPi7eJfraSlLI/6tPo6SmzjGMEkkp6SEx/WpWlOjH75MveVca4u7vQrqmXIY+MS8PHLhUsGSobpBpQd5YtplpXO04rcuH0Srs7OKw+ueaVKVjfJKPDADcU3zxzb9UvnYf3633WWtVaeGvHooM94eRrS5+WUA51w32yVudlrF6j8TBLsTjuoxPARkyTiepqCWuI71VxL2ljExcGVDQUsbjs+B0g5lVguoPWNDvORbaclCzOVM29cKOCjZu1QpVeeL777D2AV42lc98TzIm519HjRnyo8PrM2e9b11Vg/RsJT83KBquKjlz+8NxLazFsJ1Z/JA9UoGLRvP1y1UMcD8KohPAVaQPlgW+kYfR3xSJBdhwEpByfEqEEbDY3zQS1286kVunad+YOTIoMd2+D0xc1k6iTrF+VuI8CB84SXj0XeC7YKSARtQozERs55+vEZzlGuT28NDKMn3FtjY+bSzVycyCdaGQ6npz1/PLFEvlHYxJ4kyiqF/9hrnoSe4e9DllYYDJVEcvPzZME9Vr0Gjjtb2gbueVWJU5iRC4aMzOV4oJvvdPH7ksv+Bo2qFGRdin3XCbSGMnLcADME+EwaF68fmVCk05jA1e1W7JLx/5JRwrWGZIXJcT8=" # AWS_ACCESS_KEY_ID
    - secure: "a5GRgtIwYzGXm6QDZxMfKfLinBTt3hrag5XYYvHzUZgPXzo2R8rhINlVX8P7sw9vBMn28Ih//gb1u4uYlatOKTQhAU1B2FZCJUqua8wJr5ZRJuaY5JV4X6kK1liwO9zjmF3oBG24zWrwUQk6KBRhurDj/3DXCCXZOtTs8WKmzPnRnLaTlOeU2D0UVauSBIGAqs2DQD/ZXlPgu4PlmWN92Jj3SNfIki1PoLv3ohFGA54pChGEG1rNa3l9exe3wK7M2ShD1WeLWeFPedieWwZMQNzRZkw8LBbYzEIci14NmhiolBoGVKU+1dTlnJZZTWy9VOlkJG7v6pUm5X0vLCJKml1mwT63nUrK16mrWnCBTw5HsnQEUJnhkoGwE++x2p71tnxkvvkTTwKZWrMTW/0AzK/gjb8DtVbKd+ZOGiaRJFKgBpXC3zBLb0WfqhWR61LpCPnsMRCHUdW7SiUGXdsv97agZVCrGfU84f3EUOZhs/TA7VvDvfdEtQc2JhXCQQOoJnFfsIXP83sDzjECY4uDOzQopllJdklGgC3Ik0GnROpO+7jc4JmwVgP9zvgv79d22EnDDLD4gyBAX1N4CbqmgSwVrIV/94FjWFaJJhg75lXCnJNlcDTONlgvihpoIjYCX+kYt/dytjl72w2ud3jT0BY9hBU4b34G2kxkJvIEVxs=" # AWS_SECRET_ACCESS_KEY
